const ACTIONS = {
    SET_ERROR: 'SET_ERROR',
    SET_TEXT: 'SET_TEXT',
    SET_LANG: 'SET_LANG',
    SET_INDEX: 'SET_INDEX',
    SET_START: 'SET_START',
    SET_ACCURACY: 'SET_ACCURACY',
    SET_STARTTIME: 'SET_STARTTIME',
    SET_SPEED: 'SET_SPEED',
    SET_FINISH: 'SET_FINISH',
    SET_RESET: 'SET_RESET',
}

export default ACTIONS;